import test from '@playwright/test'
test("Sale Force File Upload",async({page})=>{
    await page.goto("https://login.salesforce.com/")
    await page.locator("#username").fill("dilipkumar.rajendran@testleaf.com")
    await page.locator("#password").fill("TestLeaf@2025")
    await page.locator("#Login").click()
    await page.locator(".slds-icon-waffle").click()
    await page.locator("//button[text()='View All']").click()
    //await page.waitForTimeout(3000)
    await page.locator("//p[text()='Accounts']").click()
    await page.locator("//div[@title='New']").click()
    await page.locator("//input[@name='Name']").fill("Hemavathy")
    //await page.getByPlaceholder("Search Accounts...").click()
    await page.getByRole("combobox").nth(1).click()
    await page.locator("//span[text()='Prospect']").click()
    await page.locator("//button[@class='slds-combobox__input slds-input_faux fix-slds-input_faux slds-combobox__input-value']").last().click()
    await page.locator("//span[text()='Banking']").click()
    await page.locator("//button[@name='SaveEdit']").click()
    const msg=await page.locator("//span[@class='toastMessage slds-text-heading--small forceActionsText']").innerText()
    console.log("Toast Message is: "+msg)
    await page.locator("//input[@type='file']").last().setInputFiles("TestData/Hemavathy Resume.pdf")
    await page.locator("//span[text()='Done']").click()
    const uploadmsg=await page.locator('//div/span[@class="toastMessage slds-text-heading--small forceActionsText"]').innerText()
    console.log("File Upload Message is: "+uploadmsg)

})